# Generated by Django 4.2 on 2023-04-26 04:47

from django.db import migrations, models
import streamfield.field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=128, verbose_name='header')),
                ('slug', models.SlugField(verbose_name='slug')),
                ('stream', streamfield.field.models.StreamField(default=list, verbose_name='stream')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
            },
        ),
    ]
