# Generated by Django 4.1 on 2022-08-17 13:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headerblock',
            name='level',
        ),
        migrations.AddField(
            model_name='headerblock',
            name='rank',
            field=models.PositiveSmallIntegerField(default=1, help_text='The most important heading has the rank 1 (&lt;h1&gt;), the least important heading rank 6 (&lt;h6&gt;). Headings with an equal or higher rank start a new section, headings with a lower rank start new subsections that are part of the higher ranked section.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='rank'),
        ),
    ]
