# Generated by Django 4.1 on 2022-08-18 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0002_remove_headerblock_level_headerblock_rank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='headerblock',
            old_name='header',
            new_name='text',
        ),
    ]
