# Generated by Django 4.2 on 2023-04-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0003_alter_headerblock_options_alter_imageblock_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageblock',
            name='image',
            field=models.URLField(verbose_name='image'),
        ),
    ]
