# Generated by Django 4.1 on 2022-08-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0003_rename_header_headerblock_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headerblock',
            name='text',
            field=models.CharField(max_length=255, verbose_name='text'),
        ),
    ]
